name: ThePermissionManager
main: jasonwynn10\PermMgr\ThePermissionManager
version: 0.1.2
api:
 - 3.0.0
 - 3.0.0-ALPHA7
author: "jasonwynn10"
description: "A modern Permission Manager for PMMP servers"
load: STARTUP
extensions:
 - yaml
permissions:
  PermManager:
    default: op
    children:
      PermManager.command:
        default: op
        children:
          PermManager.command.setuserpermission:
            default: op
          PermManager.command.unsetuserpermission:
            default: op
          PermManager.command.listuserpermissions:
            default: true
          PermManager.command.reloadpermissions:
            default: op
          PermManager.command.pluginpermissions:
            default: true
          PermManager.command.setgrouppermission:
            default: op
          PermManager.command.unsetgrouppermission:
            default: op